wip38

diff --git a/.github/workflows/build-wheels.yaml b/.github/workflows/build-wheels.yaml
--- a/.github/workflows/build-wheels.yaml
+++ b/.github/workflows/build-wheels.yaml
@@ -52,6 +52,8 @@ jobs:
         env:
           GK_BUILD_WHEELS: "1"
           CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
+          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
+          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
 
       - if: ${{ steps.restore_linux_wheels.outputs.cache-hit != 'true' }}
         name: Test wheels across Python 3.9–3.12
@@ -85,98 +87,98 @@ jobs:
           path: wheelhouse/*.whl
 
 
-  build-wheel-macos:
-    name: Build macos wheels
-    runs-on: macos-14
+#  build-wheel-macos:
+#    name: Build macos wheels
+#    runs-on: macos-14
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: try to restore the macos wheels cache
+#        id: restore_macos_wheels
+#        uses: actions/cache/restore@v4
+#        with:
+#          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
+#          path: wheelhouse/*.whl
+#
+#      # skip remaining steps on cache hit
+#
+#      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
+#        name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: '3.12'
+#
+#      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
+#        name: Install cibuildwheel
+#        run: python -m pip install cibuildwheel==2.23.3
+#
+#      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
+#        name: Build wheels
+#        run: python -m cibuildwheel --output-dir wheelhouse && ls -l wheelhouse/
+#        env:
+#          GK_BUILD_WHEELS: "1"
+#          CIBW_ARCHS_MACOS: x86_64 arm64
+#          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
+#
+#      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
+#        name: cache macos wheels
+#        uses: actions/cache/save@v4
+#        with:
+#          # hashFiles() would produce a different key due to setup/*.pyc files created
+#          key: ${{ steps.restore_macos_wheels.outputs.cache-primary-key }}
+#          path: wheelhouse/*.whl
 
-    steps:
-      - uses: actions/checkout@v4
 
-      - name: try to restore the macos wheels cache
-        id: restore_macos_wheels
-        uses: actions/cache/restore@v4
-        with:
-          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
-          path: wheelhouse/*.whl
-
-      # skip remaining steps on cache hit
-
-      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
-        name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.12'
-
-      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
-        name: Install cibuildwheel
-        run: python -m pip install cibuildwheel==2.23.3
-
-      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
-        name: Build wheels
-        run: python -m cibuildwheel --output-dir wheelhouse && ls -l wheelhouse/
-        env:
-          GK_BUILD_WHEELS: "1"
-          CIBW_ARCHS_MACOS: x86_64 arm64
-          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
-
-      - if: ${{ steps.restore_macos_wheels.outputs.cache-hit != 'true' }}
-        name: cache macos wheels
-        uses: actions/cache/save@v4
-        with:
-          # hashFiles() would produce a different key due to setup/*.pyc files created
-          key: ${{ steps.restore_macos_wheels.outputs.cache-primary-key }}
-          path: wheelhouse/*.whl
-
-
-  test-wheel-macos:
-    needs: build-wheel-macos
-    name: Test wheels on ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        include:
-          # macos-14 == arm64, macos-13 == x86_64
-          - {"os": "macos-14", "arch": "arm64", "pyver": "3.9", "pyvershort": "39"}
-          - {"os": "macos-14", "arch": "arm64", "pyver": "3.10", "pyvershort": "310"}
-          - {"os": "macos-14", "arch": "arm64", "pyver": "3.11", "pyvershort": "311"}
-          - {"os": "macos-14", "arch": "arm64", "pyver": "3.12", "pyvershort": "312"}
-          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.9", "pyvershort": "39"}
-          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.10", "pyvershort": "310"}
-          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.11", "pyvershort": "311"}
-          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.12", "pyvershort": "312"}
-
-    steps:
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.pyver }}
-
-      - uses: actions/checkout@v4
-
-      - name: Download built wheels
-        uses: actions/cache/restore@v4
-        with:
-          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
-          path: wheelhouse/*.whl
-          fail-on-cache-miss: true
-
-      - name: Verify GK module loads
-        run: |
-          set -euxo pipefail
-          ls -l wheelhouse/*cp${{ matrix.pyvershort }}*${{ matrix.arch }}.whl
-          mv wheelhouse /tmp/
-          pushd /tmp # navigate away from repo dir to avoid loading the local files
-          pip install wheelhouse/*cp${{ matrix.pyvershort }}*${{ matrix.arch }}.whl
-          python -c 'import genome_kit; print(genome_kit.__version__)'
-          popd
-
-      - name: Run unit tests
-        run: |
-          set -euxo pipefail
-          mv tests /tmp/
-          pushd /tmp
-          ls tests/test_*.py | sed 's/\.py$//' | sed 's/tests\//tests./' | CI=1 xargs -p -I {} python -m unittest {}
-
+#  test-wheel-macos:
+#    needs: build-wheel-macos
+#    name: Test wheels on ${{ matrix.os }}
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      matrix:
+#        include:
+#          # macos-14 == arm64, macos-13 == x86_64
+#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.9", "pyvershort": "39"}
+#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.10", "pyvershort": "310"}
+#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.11", "pyvershort": "311"}
+#          - {"os": "macos-14", "arch": "arm64", "pyver": "3.12", "pyvershort": "312"}
+#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.9", "pyvershort": "39"}
+#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.10", "pyvershort": "310"}
+#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.11", "pyvershort": "311"}
+#          - {"os": "macos-13", "arch": "x86_64", "pyver": "3.12", "pyvershort": "312"}
+#
+#    steps:
+#      - name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: ${{ matrix.pyver }}
+#
+#      - uses: actions/checkout@v4
+#
+#      - name: Download built wheels
+#        uses: actions/cache/restore@v4
+#        with:
+#          key: macos-wheels-${{ hashFiles('.github/workflows/build-wheels.yaml', '.github/actions/**', 'src/**', 'genome_kit/**', 'pyproject.toml', 'setup.py', 'setup/**') }}
+#          path: wheelhouse/*.whl
+#          fail-on-cache-miss: true
+#
+#      - name: Verify GK module loads
+#        run: |
+#          set -euxo pipefail
+#          ls -l wheelhouse/*cp${{ matrix.pyvershort }}*${{ matrix.arch }}.whl
+#          mv wheelhouse /tmp/
+#          pushd /tmp # navigate away from repo dir to avoid loading the local files
+#          pip install wheelhouse/*cp${{ matrix.pyvershort }}*${{ matrix.arch }}.whl
+#          python -c 'import genome_kit; print(genome_kit.__version__)'
+#          popd
+#
+#      - name: Run unit tests
+#        run: |
+#          set -euxo pipefail
+#          mv tests /tmp/
+#          pushd /tmp
+#          ls tests/test_*.py | sed 's/\.py$//' | sed 's/tests\//tests./' | CI=1 xargs -p -I {} python -m unittest {}
+#
 
 #  publish-to-pypi:
 #    needs: [build-wheel-linux, test-wheel-macos]
